import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import tickSvg from '../public/tick.svg';
import wrongPng from '../public/wrong.png';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <div style={{ fontSize: 60 }}>
          4 + 6 = 
          <input type="text" style={{ width: 100, fontSize: 60 }} />
        </div>
        <Image src={tickSvg} width={100} height={100} />
        <Image src={wrongPng} width={100} height={100} />
      </main>
    </div>
  )
}

export default Home
